// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eval1.Models;

public partial class Trainee
{
    public int TraineeId { get; set; }

    public string TraineeName { get; set; }

    public string Location { get; set; }

    public int? Points { get; set; }

    public string Description { get; set; }
}